// source: model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.api_proto.AnswerValue');
goog.provide('proto.api_proto.AnswerValue.AnswerCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api_proto.AnswerValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.api_proto.AnswerValue.oneofGroups_);
};
goog.inherits(proto.api_proto.AnswerValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api_proto.AnswerValue.displayName = 'proto.api_proto.AnswerValue';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.api_proto.AnswerValue.oneofGroups_ = [[1,2,3,4]];

/**
 * @enum {number}
 */
proto.api_proto.AnswerValue.AnswerCase = {
  ANSWER_NOT_SET: 0,
  BOOLEAN_VALUE: 1,
  INTEGER_VALUE: 2,
  DOUBLE_VALUE: 3,
  TEXT_VALUE: 4
};

/**
 * @return {proto.api_proto.AnswerValue.AnswerCase}
 */
proto.api_proto.AnswerValue.prototype.getAnswerCase = function() {
  return /** @type {proto.api_proto.AnswerValue.AnswerCase} */(jspb.Message.computeOneofCase(this, proto.api_proto.AnswerValue.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api_proto.AnswerValue.prototype.toObject = function(opt_includeInstance) {
  return proto.api_proto.AnswerValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api_proto.AnswerValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.AnswerValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    booleanValue: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    integerValue: jspb.Message.getFieldWithDefault(msg, 2, 0),
    doubleValue: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    textValue: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api_proto.AnswerValue}
 */
proto.api_proto.AnswerValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api_proto.AnswerValue;
  return proto.api_proto.AnswerValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api_proto.AnswerValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api_proto.AnswerValue}
 */
proto.api_proto.AnswerValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBooleanValue(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setIntegerValue(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDoubleValue(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTextValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api_proto.AnswerValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api_proto.AnswerValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api_proto.AnswerValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.AnswerValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {boolean} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBool(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional bool boolean_value = 1;
 * @return {boolean}
 */
proto.api_proto.AnswerValue.prototype.getBooleanValue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.api_proto.AnswerValue} returns this
 */
proto.api_proto.AnswerValue.prototype.setBooleanValue = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.api_proto.AnswerValue.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.api_proto.AnswerValue} returns this
 */
proto.api_proto.AnswerValue.prototype.clearBooleanValue = function() {
  return jspb.Message.setOneofField(this, 1, proto.api_proto.AnswerValue.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.AnswerValue.prototype.hasBooleanValue = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint32 integer_value = 2;
 * @return {number}
 */
proto.api_proto.AnswerValue.prototype.getIntegerValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.AnswerValue} returns this
 */
proto.api_proto.AnswerValue.prototype.setIntegerValue = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.api_proto.AnswerValue.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.api_proto.AnswerValue} returns this
 */
proto.api_proto.AnswerValue.prototype.clearIntegerValue = function() {
  return jspb.Message.setOneofField(this, 2, proto.api_proto.AnswerValue.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.AnswerValue.prototype.hasIntegerValue = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional double double_value = 3;
 * @return {number}
 */
proto.api_proto.AnswerValue.prototype.getDoubleValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.AnswerValue} returns this
 */
proto.api_proto.AnswerValue.prototype.setDoubleValue = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.api_proto.AnswerValue.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.api_proto.AnswerValue} returns this
 */
proto.api_proto.AnswerValue.prototype.clearDoubleValue = function() {
  return jspb.Message.setOneofField(this, 3, proto.api_proto.AnswerValue.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.AnswerValue.prototype.hasDoubleValue = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string text_value = 4;
 * @return {string}
 */
proto.api_proto.AnswerValue.prototype.getTextValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.AnswerValue} returns this
 */
proto.api_proto.AnswerValue.prototype.setTextValue = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.api_proto.AnswerValue.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.api_proto.AnswerValue} returns this
 */
proto.api_proto.AnswerValue.prototype.clearTextValue = function() {
  return jspb.Message.setOneofField(this, 4, proto.api_proto.AnswerValue.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.AnswerValue.prototype.hasTextValue = function() {
  return jspb.Message.getField(this, 4) != null;
};


