// source: model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.api_proto.DefaultAnswerOption');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api_proto.AnswerValue');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api_proto.DefaultAnswerOption = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api_proto.DefaultAnswerOption, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api_proto.DefaultAnswerOption.displayName = 'proto.api_proto.DefaultAnswerOption';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api_proto.DefaultAnswerOption.prototype.toObject = function(opt_includeInstance) {
  return proto.api_proto.DefaultAnswerOption.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api_proto.DefaultAnswerOption} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.DefaultAnswerOption.toObject = function(includeInstance, msg) {
  var f, obj = {
    displayText: jspb.Message.getFieldWithDefault(msg, 1, ""),
    iconUrl: jspb.Message.getFieldWithDefault(msg, 2, ""),
    colorHex: jspb.Message.getFieldWithDefault(msg, 3, ""),
    answerValue: (f = msg.getAnswerValue()) && proto.api_proto.AnswerValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api_proto.DefaultAnswerOption}
 */
proto.api_proto.DefaultAnswerOption.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api_proto.DefaultAnswerOption;
  return proto.api_proto.DefaultAnswerOption.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api_proto.DefaultAnswerOption} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api_proto.DefaultAnswerOption}
 */
proto.api_proto.DefaultAnswerOption.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDisplayText(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIconUrl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setColorHex(value);
      break;
    case 4:
      var value = new proto.api_proto.AnswerValue;
      reader.readMessage(value,proto.api_proto.AnswerValue.deserializeBinaryFromReader);
      msg.setAnswerValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api_proto.DefaultAnswerOption.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api_proto.DefaultAnswerOption.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api_proto.DefaultAnswerOption} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.DefaultAnswerOption.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDisplayText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIconUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getColorHex();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAnswerValue();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.api_proto.AnswerValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional string display_text = 1;
 * @return {string}
 */
proto.api_proto.DefaultAnswerOption.prototype.getDisplayText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.DefaultAnswerOption} returns this
 */
proto.api_proto.DefaultAnswerOption.prototype.setDisplayText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string icon_url = 2;
 * @return {string}
 */
proto.api_proto.DefaultAnswerOption.prototype.getIconUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.DefaultAnswerOption} returns this
 */
proto.api_proto.DefaultAnswerOption.prototype.setIconUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string color_hex = 3;
 * @return {string}
 */
proto.api_proto.DefaultAnswerOption.prototype.getColorHex = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.DefaultAnswerOption} returns this
 */
proto.api_proto.DefaultAnswerOption.prototype.setColorHex = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional AnswerValue answer_value = 4;
 * @return {?proto.api_proto.AnswerValue}
 */
proto.api_proto.DefaultAnswerOption.prototype.getAnswerValue = function() {
  return /** @type{?proto.api_proto.AnswerValue} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.AnswerValue, 4));
};


/**
 * @param {?proto.api_proto.AnswerValue|undefined} value
 * @return {!proto.api_proto.DefaultAnswerOption} returns this
*/
proto.api_proto.DefaultAnswerOption.prototype.setAnswerValue = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.DefaultAnswerOption} returns this
 */
proto.api_proto.DefaultAnswerOption.prototype.clearAnswerValue = function() {
  return this.setAnswerValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.DefaultAnswerOption.prototype.hasAnswerValue = function() {
  return jspb.Message.getField(this, 4) != null;
};


