// source: model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.api_proto.DefaultQuestion');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api_proto.DefaultAnswerOption');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api_proto.DefaultQuestion = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api_proto.DefaultQuestion.repeatedFields_, null);
};
goog.inherits(proto.api_proto.DefaultQuestion, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api_proto.DefaultQuestion.displayName = 'proto.api_proto.DefaultQuestion';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api_proto.DefaultQuestion.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api_proto.DefaultQuestion.prototype.toObject = function(opt_includeInstance) {
  return proto.api_proto.DefaultQuestion.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api_proto.DefaultQuestion} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.DefaultQuestion.toObject = function(includeInstance, msg) {
  var f, obj = {
    defaultQuestionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    askerDisplayText: jspb.Message.getFieldWithDefault(msg, 2, ""),
    answererDisplayText: jspb.Message.getFieldWithDefault(msg, 3, ""),
    price: jspb.Message.getFieldWithDefault(msg, 4, 0),
    numUsersWaiting: jspb.Message.getFieldWithDefault(msg, 5, 0),
    lastAnsweredAt: jspb.Message.getFieldWithDefault(msg, 6, 0),
    answerOptionsList: jspb.Message.toObjectList(msg.getAnswerOptionsList(),
    proto.api_proto.DefaultAnswerOption.toObject, includeInstance),
    lastFollowedAt: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api_proto.DefaultQuestion}
 */
proto.api_proto.DefaultQuestion.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api_proto.DefaultQuestion;
  return proto.api_proto.DefaultQuestion.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api_proto.DefaultQuestion} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api_proto.DefaultQuestion}
 */
proto.api_proto.DefaultQuestion.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDefaultQuestionId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAskerDisplayText(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnswererDisplayText(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPrice(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNumUsersWaiting(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLastAnsweredAt(value);
      break;
    case 7:
      var value = new proto.api_proto.DefaultAnswerOption;
      reader.readMessage(value,proto.api_proto.DefaultAnswerOption.deserializeBinaryFromReader);
      msg.addAnswerOptions(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLastFollowedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api_proto.DefaultQuestion.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api_proto.DefaultQuestion.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api_proto.DefaultQuestion} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.DefaultQuestion.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDefaultQuestionId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAskerDisplayText();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAnswererDisplayText();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getNumUsersWaiting();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getLastAnsweredAt();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getAnswerOptionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.api_proto.DefaultAnswerOption.serializeBinaryToWriter
    );
  }
  f = message.getLastFollowedAt();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
};


/**
 * optional string default_question_id = 1;
 * @return {string}
 */
proto.api_proto.DefaultQuestion.prototype.getDefaultQuestionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.DefaultQuestion} returns this
 */
proto.api_proto.DefaultQuestion.prototype.setDefaultQuestionId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string asker_display_text = 2;
 * @return {string}
 */
proto.api_proto.DefaultQuestion.prototype.getAskerDisplayText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.DefaultQuestion} returns this
 */
proto.api_proto.DefaultQuestion.prototype.setAskerDisplayText = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string answerer_display_text = 3;
 * @return {string}
 */
proto.api_proto.DefaultQuestion.prototype.getAnswererDisplayText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.DefaultQuestion} returns this
 */
proto.api_proto.DefaultQuestion.prototype.setAnswererDisplayText = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 price = 4;
 * @return {number}
 */
proto.api_proto.DefaultQuestion.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.DefaultQuestion} returns this
 */
proto.api_proto.DefaultQuestion.prototype.setPrice = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 num_users_waiting = 5;
 * @return {number}
 */
proto.api_proto.DefaultQuestion.prototype.getNumUsersWaiting = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.DefaultQuestion} returns this
 */
proto.api_proto.DefaultQuestion.prototype.setNumUsersWaiting = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint64 last_answered_at = 6;
 * @return {number}
 */
proto.api_proto.DefaultQuestion.prototype.getLastAnsweredAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.DefaultQuestion} returns this
 */
proto.api_proto.DefaultQuestion.prototype.setLastAnsweredAt = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated DefaultAnswerOption answer_options = 7;
 * @return {!Array<!proto.api_proto.DefaultAnswerOption>}
 */
proto.api_proto.DefaultQuestion.prototype.getAnswerOptionsList = function() {
  return /** @type{!Array<!proto.api_proto.DefaultAnswerOption>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api_proto.DefaultAnswerOption, 7));
};


/**
 * @param {!Array<!proto.api_proto.DefaultAnswerOption>} value
 * @return {!proto.api_proto.DefaultQuestion} returns this
*/
proto.api_proto.DefaultQuestion.prototype.setAnswerOptionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.api_proto.DefaultAnswerOption=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api_proto.DefaultAnswerOption}
 */
proto.api_proto.DefaultQuestion.prototype.addAnswerOptions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.api_proto.DefaultAnswerOption, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api_proto.DefaultQuestion} returns this
 */
proto.api_proto.DefaultQuestion.prototype.clearAnswerOptionsList = function() {
  return this.setAnswerOptionsList([]);
};


/**
 * optional uint64 last_followed_at = 8;
 * @return {number}
 */
proto.api_proto.DefaultQuestion.prototype.getLastFollowedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.DefaultQuestion} returns this
 */
proto.api_proto.DefaultQuestion.prototype.setLastFollowedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


