// source: model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.api_proto.FullSpace4_2');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api_proto.FullCustomQuestion4_2');
goog.require('proto.api_proto.FullDefaultQuestion4_2');
goog.require('proto.api_proto.Space');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api_proto.FullSpace4_2 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api_proto.FullSpace4_2.repeatedFields_, null);
};
goog.inherits(proto.api_proto.FullSpace4_2, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api_proto.FullSpace4_2.displayName = 'proto.api_proto.FullSpace4_2';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api_proto.FullSpace4_2.repeatedFields_ = [3,6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api_proto.FullSpace4_2.prototype.toObject = function(opt_includeInstance) {
  return proto.api_proto.FullSpace4_2.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api_proto.FullSpace4_2} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.FullSpace4_2.toObject = function(includeInstance, msg) {
  var f, obj = {
    space: (f = msg.getSpace()) && proto.api_proto.Space.toObject(includeInstance, f),
    defaultQuestion: (f = msg.getDefaultQuestion()) && proto.api_proto.FullDefaultQuestion4_2.toObject(includeInstance, f),
    customQuestionList: jspb.Message.toObjectList(msg.getCustomQuestionList(),
    proto.api_proto.FullCustomQuestion4_2.toObject, includeInstance),
    scores: jspb.Message.getFieldWithDefault(msg, 4, 0),
    predictedBusyness: jspb.Message.getFieldWithDefault(msg, 5, ""),
    otherDefaultQuestionsList: jspb.Message.toObjectList(msg.getOtherDefaultQuestionsList(),
    proto.api_proto.FullDefaultQuestion4_2.toObject, includeInstance),
    expiredCustomQuestionsList: jspb.Message.toObjectList(msg.getExpiredCustomQuestionsList(),
    proto.api_proto.FullCustomQuestion4_2.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api_proto.FullSpace4_2}
 */
proto.api_proto.FullSpace4_2.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api_proto.FullSpace4_2;
  return proto.api_proto.FullSpace4_2.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api_proto.FullSpace4_2} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api_proto.FullSpace4_2}
 */
proto.api_proto.FullSpace4_2.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api_proto.Space;
      reader.readMessage(value,proto.api_proto.Space.deserializeBinaryFromReader);
      msg.setSpace(value);
      break;
    case 2:
      var value = new proto.api_proto.FullDefaultQuestion4_2;
      reader.readMessage(value,proto.api_proto.FullDefaultQuestion4_2.deserializeBinaryFromReader);
      msg.setDefaultQuestion(value);
      break;
    case 3:
      var value = new proto.api_proto.FullCustomQuestion4_2;
      reader.readMessage(value,proto.api_proto.FullCustomQuestion4_2.deserializeBinaryFromReader);
      msg.addCustomQuestion(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScores(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPredictedBusyness(value);
      break;
    case 6:
      var value = new proto.api_proto.FullDefaultQuestion4_2;
      reader.readMessage(value,proto.api_proto.FullDefaultQuestion4_2.deserializeBinaryFromReader);
      msg.addOtherDefaultQuestions(value);
      break;
    case 7:
      var value = new proto.api_proto.FullCustomQuestion4_2;
      reader.readMessage(value,proto.api_proto.FullCustomQuestion4_2.deserializeBinaryFromReader);
      msg.addExpiredCustomQuestions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api_proto.FullSpace4_2.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api_proto.FullSpace4_2.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api_proto.FullSpace4_2} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.FullSpace4_2.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpace();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api_proto.Space.serializeBinaryToWriter
    );
  }
  f = message.getDefaultQuestion();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.api_proto.FullDefaultQuestion4_2.serializeBinaryToWriter
    );
  }
  f = message.getCustomQuestionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.api_proto.FullCustomQuestion4_2.serializeBinaryToWriter
    );
  }
  f = message.getScores();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getPredictedBusyness();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getOtherDefaultQuestionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.api_proto.FullDefaultQuestion4_2.serializeBinaryToWriter
    );
  }
  f = message.getExpiredCustomQuestionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.api_proto.FullCustomQuestion4_2.serializeBinaryToWriter
    );
  }
};


/**
 * optional Space space = 1;
 * @return {?proto.api_proto.Space}
 */
proto.api_proto.FullSpace4_2.prototype.getSpace = function() {
  return /** @type{?proto.api_proto.Space} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.Space, 1));
};


/**
 * @param {?proto.api_proto.Space|undefined} value
 * @return {!proto.api_proto.FullSpace4_2} returns this
*/
proto.api_proto.FullSpace4_2.prototype.setSpace = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.FullSpace4_2} returns this
 */
proto.api_proto.FullSpace4_2.prototype.clearSpace = function() {
  return this.setSpace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.FullSpace4_2.prototype.hasSpace = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional FullDefaultQuestion4_2 default_question = 2;
 * @return {?proto.api_proto.FullDefaultQuestion4_2}
 */
proto.api_proto.FullSpace4_2.prototype.getDefaultQuestion = function() {
  return /** @type{?proto.api_proto.FullDefaultQuestion4_2} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.FullDefaultQuestion4_2, 2));
};


/**
 * @param {?proto.api_proto.FullDefaultQuestion4_2|undefined} value
 * @return {!proto.api_proto.FullSpace4_2} returns this
*/
proto.api_proto.FullSpace4_2.prototype.setDefaultQuestion = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.FullSpace4_2} returns this
 */
proto.api_proto.FullSpace4_2.prototype.clearDefaultQuestion = function() {
  return this.setDefaultQuestion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.FullSpace4_2.prototype.hasDefaultQuestion = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated FullCustomQuestion4_2 custom_question = 3;
 * @return {!Array<!proto.api_proto.FullCustomQuestion4_2>}
 */
proto.api_proto.FullSpace4_2.prototype.getCustomQuestionList = function() {
  return /** @type{!Array<!proto.api_proto.FullCustomQuestion4_2>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api_proto.FullCustomQuestion4_2, 3));
};


/**
 * @param {!Array<!proto.api_proto.FullCustomQuestion4_2>} value
 * @return {!proto.api_proto.FullSpace4_2} returns this
*/
proto.api_proto.FullSpace4_2.prototype.setCustomQuestionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.api_proto.FullCustomQuestion4_2=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api_proto.FullCustomQuestion4_2}
 */
proto.api_proto.FullSpace4_2.prototype.addCustomQuestion = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.api_proto.FullCustomQuestion4_2, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api_proto.FullSpace4_2} returns this
 */
proto.api_proto.FullSpace4_2.prototype.clearCustomQuestionList = function() {
  return this.setCustomQuestionList([]);
};


/**
 * optional int32 scores = 4;
 * @return {number}
 */
proto.api_proto.FullSpace4_2.prototype.getScores = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.FullSpace4_2} returns this
 */
proto.api_proto.FullSpace4_2.prototype.setScores = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string predicted_busyness = 5;
 * @return {string}
 */
proto.api_proto.FullSpace4_2.prototype.getPredictedBusyness = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.FullSpace4_2} returns this
 */
proto.api_proto.FullSpace4_2.prototype.setPredictedBusyness = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated FullDefaultQuestion4_2 other_default_questions = 6;
 * @return {!Array<!proto.api_proto.FullDefaultQuestion4_2>}
 */
proto.api_proto.FullSpace4_2.prototype.getOtherDefaultQuestionsList = function() {
  return /** @type{!Array<!proto.api_proto.FullDefaultQuestion4_2>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api_proto.FullDefaultQuestion4_2, 6));
};


/**
 * @param {!Array<!proto.api_proto.FullDefaultQuestion4_2>} value
 * @return {!proto.api_proto.FullSpace4_2} returns this
*/
proto.api_proto.FullSpace4_2.prototype.setOtherDefaultQuestionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.api_proto.FullDefaultQuestion4_2=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api_proto.FullDefaultQuestion4_2}
 */
proto.api_proto.FullSpace4_2.prototype.addOtherDefaultQuestions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.api_proto.FullDefaultQuestion4_2, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api_proto.FullSpace4_2} returns this
 */
proto.api_proto.FullSpace4_2.prototype.clearOtherDefaultQuestionsList = function() {
  return this.setOtherDefaultQuestionsList([]);
};


/**
 * repeated FullCustomQuestion4_2 expired_custom_questions = 7;
 * @return {!Array<!proto.api_proto.FullCustomQuestion4_2>}
 */
proto.api_proto.FullSpace4_2.prototype.getExpiredCustomQuestionsList = function() {
  return /** @type{!Array<!proto.api_proto.FullCustomQuestion4_2>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api_proto.FullCustomQuestion4_2, 7));
};


/**
 * @param {!Array<!proto.api_proto.FullCustomQuestion4_2>} value
 * @return {!proto.api_proto.FullSpace4_2} returns this
*/
proto.api_proto.FullSpace4_2.prototype.setExpiredCustomQuestionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.api_proto.FullCustomQuestion4_2=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api_proto.FullCustomQuestion4_2}
 */
proto.api_proto.FullSpace4_2.prototype.addExpiredCustomQuestions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.api_proto.FullCustomQuestion4_2, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api_proto.FullSpace4_2} returns this
 */
proto.api_proto.FullSpace4_2.prototype.clearExpiredCustomQuestionsList = function() {
  return this.setExpiredCustomQuestionsList([]);
};


