// source: model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.api_proto.FullDefaultQuestion4_2');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api_proto.Answer4_2');
goog.require('proto.api_proto.DefaultQuestion');
goog.require('proto.api_proto.Space');
goog.require('proto.api_proto.User4_2');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api_proto.FullDefaultQuestion4_2 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api_proto.FullDefaultQuestion4_2.repeatedFields_, null);
};
goog.inherits(proto.api_proto.FullDefaultQuestion4_2, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api_proto.FullDefaultQuestion4_2.displayName = 'proto.api_proto.FullDefaultQuestion4_2';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api_proto.FullDefaultQuestion4_2.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.toObject = function(opt_includeInstance) {
  return proto.api_proto.FullDefaultQuestion4_2.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api_proto.FullDefaultQuestion4_2} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.FullDefaultQuestion4_2.toObject = function(includeInstance, msg) {
  var f, obj = {
    question: (f = msg.getQuestion()) && proto.api_proto.DefaultQuestion.toObject(includeInstance, f),
    space: (f = msg.getSpace()) && proto.api_proto.Space.toObject(includeInstance, f),
    answersList: jspb.Message.toObjectList(msg.getAnswersList(),
    proto.api_proto.Answer4_2.toObject, includeInstance),
    waitingAskersList: jspb.Message.toObjectList(msg.getWaitingAskersList(),
    proto.api_proto.User4_2.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api_proto.FullDefaultQuestion4_2}
 */
proto.api_proto.FullDefaultQuestion4_2.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api_proto.FullDefaultQuestion4_2;
  return proto.api_proto.FullDefaultQuestion4_2.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api_proto.FullDefaultQuestion4_2} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api_proto.FullDefaultQuestion4_2}
 */
proto.api_proto.FullDefaultQuestion4_2.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api_proto.DefaultQuestion;
      reader.readMessage(value,proto.api_proto.DefaultQuestion.deserializeBinaryFromReader);
      msg.setQuestion(value);
      break;
    case 2:
      var value = new proto.api_proto.Space;
      reader.readMessage(value,proto.api_proto.Space.deserializeBinaryFromReader);
      msg.setSpace(value);
      break;
    case 3:
      var value = new proto.api_proto.Answer4_2;
      reader.readMessage(value,proto.api_proto.Answer4_2.deserializeBinaryFromReader);
      msg.addAnswers(value);
      break;
    case 4:
      var value = new proto.api_proto.User4_2;
      reader.readMessage(value,proto.api_proto.User4_2.deserializeBinaryFromReader);
      msg.addWaitingAskers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api_proto.FullDefaultQuestion4_2.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api_proto.FullDefaultQuestion4_2} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.FullDefaultQuestion4_2.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuestion();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api_proto.DefaultQuestion.serializeBinaryToWriter
    );
  }
  f = message.getSpace();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.api_proto.Space.serializeBinaryToWriter
    );
  }
  f = message.getAnswersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.api_proto.Answer4_2.serializeBinaryToWriter
    );
  }
  f = message.getWaitingAskersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.api_proto.User4_2.serializeBinaryToWriter
    );
  }
};


/**
 * optional DefaultQuestion question = 1;
 * @return {?proto.api_proto.DefaultQuestion}
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.getQuestion = function() {
  return /** @type{?proto.api_proto.DefaultQuestion} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.DefaultQuestion, 1));
};


/**
 * @param {?proto.api_proto.DefaultQuestion|undefined} value
 * @return {!proto.api_proto.FullDefaultQuestion4_2} returns this
*/
proto.api_proto.FullDefaultQuestion4_2.prototype.setQuestion = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.FullDefaultQuestion4_2} returns this
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.clearQuestion = function() {
  return this.setQuestion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.hasQuestion = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Space space = 2;
 * @return {?proto.api_proto.Space}
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.getSpace = function() {
  return /** @type{?proto.api_proto.Space} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.Space, 2));
};


/**
 * @param {?proto.api_proto.Space|undefined} value
 * @return {!proto.api_proto.FullDefaultQuestion4_2} returns this
*/
proto.api_proto.FullDefaultQuestion4_2.prototype.setSpace = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.FullDefaultQuestion4_2} returns this
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.clearSpace = function() {
  return this.setSpace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.hasSpace = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Answer4_2 answers = 3;
 * @return {!Array<!proto.api_proto.Answer4_2>}
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.getAnswersList = function() {
  return /** @type{!Array<!proto.api_proto.Answer4_2>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api_proto.Answer4_2, 3));
};


/**
 * @param {!Array<!proto.api_proto.Answer4_2>} value
 * @return {!proto.api_proto.FullDefaultQuestion4_2} returns this
*/
proto.api_proto.FullDefaultQuestion4_2.prototype.setAnswersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.api_proto.Answer4_2=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api_proto.Answer4_2}
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.addAnswers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.api_proto.Answer4_2, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api_proto.FullDefaultQuestion4_2} returns this
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.clearAnswersList = function() {
  return this.setAnswersList([]);
};


/**
 * repeated User4_2 waiting_askers = 4;
 * @return {!Array<!proto.api_proto.User4_2>}
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.getWaitingAskersList = function() {
  return /** @type{!Array<!proto.api_proto.User4_2>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api_proto.User4_2, 4));
};


/**
 * @param {!Array<!proto.api_proto.User4_2>} value
 * @return {!proto.api_proto.FullDefaultQuestion4_2} returns this
*/
proto.api_proto.FullDefaultQuestion4_2.prototype.setWaitingAskersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.api_proto.User4_2=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api_proto.User4_2}
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.addWaitingAskers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.api_proto.User4_2, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api_proto.FullDefaultQuestion4_2} returns this
 */
proto.api_proto.FullDefaultQuestion4_2.prototype.clearWaitingAskersList = function() {
  return this.setWaitingAskersList([]);
};


