// source: space_server.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.api_proto.SearchSpaceByNameRequest');
goog.provide('proto.api_proto.SearchSpaceByNameRequest.InnerMessage');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api_proto.Coordinates');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api_proto.SearchSpaceByNameRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api_proto.SearchSpaceByNameRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api_proto.SearchSpaceByNameRequest.displayName = 'proto.api_proto.SearchSpaceByNameRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api_proto.SearchSpaceByNameRequest.InnerMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api_proto.SearchSpaceByNameRequest.InnerMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api_proto.SearchSpaceByNameRequest.InnerMessage.displayName = 'proto.api_proto.SearchSpaceByNameRequest.InnerMessage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api_proto.SearchSpaceByNameRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api_proto.SearchSpaceByNameRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api_proto.SearchSpaceByNameRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.SearchSpaceByNameRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    queryString: jspb.Message.getFieldWithDefault(msg, 1, ""),
    coordinates: (f = msg.getCoordinates()) && proto.api_proto.Coordinates.toObject(includeInstance, f),
    inner: (f = msg.getInner()) && proto.api_proto.SearchSpaceByNameRequest.InnerMessage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api_proto.SearchSpaceByNameRequest}
 */
proto.api_proto.SearchSpaceByNameRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api_proto.SearchSpaceByNameRequest;
  return proto.api_proto.SearchSpaceByNameRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api_proto.SearchSpaceByNameRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api_proto.SearchSpaceByNameRequest}
 */
proto.api_proto.SearchSpaceByNameRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setQueryString(value);
      break;
    case 2:
      var value = new proto.api_proto.Coordinates;
      reader.readMessage(value,proto.api_proto.Coordinates.deserializeBinaryFromReader);
      msg.setCoordinates(value);
      break;
    case 3:
      var value = new proto.api_proto.SearchSpaceByNameRequest.InnerMessage;
      reader.readMessage(value,proto.api_proto.SearchSpaceByNameRequest.InnerMessage.deserializeBinaryFromReader);
      msg.setInner(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api_proto.SearchSpaceByNameRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api_proto.SearchSpaceByNameRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api_proto.SearchSpaceByNameRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.SearchSpaceByNameRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQueryString();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCoordinates();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.api_proto.Coordinates.serializeBinaryToWriter
    );
  }
  f = message.getInner();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.api_proto.SearchSpaceByNameRequest.InnerMessage.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api_proto.SearchSpaceByNameRequest.InnerMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.api_proto.SearchSpaceByNameRequest.InnerMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api_proto.SearchSpaceByNameRequest.InnerMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.SearchSpaceByNameRequest.InnerMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    fuck: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api_proto.SearchSpaceByNameRequest.InnerMessage}
 */
proto.api_proto.SearchSpaceByNameRequest.InnerMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api_proto.SearchSpaceByNameRequest.InnerMessage;
  return proto.api_proto.SearchSpaceByNameRequest.InnerMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api_proto.SearchSpaceByNameRequest.InnerMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api_proto.SearchSpaceByNameRequest.InnerMessage}
 */
proto.api_proto.SearchSpaceByNameRequest.InnerMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFuck(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api_proto.SearchSpaceByNameRequest.InnerMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api_proto.SearchSpaceByNameRequest.InnerMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api_proto.SearchSpaceByNameRequest.InnerMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.SearchSpaceByNameRequest.InnerMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFuck();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string fuck = 1;
 * @return {string}
 */
proto.api_proto.SearchSpaceByNameRequest.InnerMessage.prototype.getFuck = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.SearchSpaceByNameRequest.InnerMessage} returns this
 */
proto.api_proto.SearchSpaceByNameRequest.InnerMessage.prototype.setFuck = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string query_string = 1;
 * @return {string}
 */
proto.api_proto.SearchSpaceByNameRequest.prototype.getQueryString = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.SearchSpaceByNameRequest} returns this
 */
proto.api_proto.SearchSpaceByNameRequest.prototype.setQueryString = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Coordinates coordinates = 2;
 * @return {?proto.api_proto.Coordinates}
 */
proto.api_proto.SearchSpaceByNameRequest.prototype.getCoordinates = function() {
  return /** @type{?proto.api_proto.Coordinates} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.Coordinates, 2));
};


/**
 * @param {?proto.api_proto.Coordinates|undefined} value
 * @return {!proto.api_proto.SearchSpaceByNameRequest} returns this
*/
proto.api_proto.SearchSpaceByNameRequest.prototype.setCoordinates = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.SearchSpaceByNameRequest} returns this
 */
proto.api_proto.SearchSpaceByNameRequest.prototype.clearCoordinates = function() {
  return this.setCoordinates(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.SearchSpaceByNameRequest.prototype.hasCoordinates = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional InnerMessage inner = 3;
 * @return {?proto.api_proto.SearchSpaceByNameRequest.InnerMessage}
 */
proto.api_proto.SearchSpaceByNameRequest.prototype.getInner = function() {
  return /** @type{?proto.api_proto.SearchSpaceByNameRequest.InnerMessage} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.SearchSpaceByNameRequest.InnerMessage, 3));
};


/**
 * @param {?proto.api_proto.SearchSpaceByNameRequest.InnerMessage|undefined} value
 * @return {!proto.api_proto.SearchSpaceByNameRequest} returns this
*/
proto.api_proto.SearchSpaceByNameRequest.prototype.setInner = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.SearchSpaceByNameRequest} returns this
 */
proto.api_proto.SearchSpaceByNameRequest.prototype.clearInner = function() {
  return this.setInner(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.SearchSpaceByNameRequest.prototype.hasInner = function() {
  return jspb.Message.getField(this, 3) != null;
};


