// source: space_server.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.api_proto.SpaceServerRequests');
goog.provide('proto.api_proto.SpaceServerRequests.RequestCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api_proto.AddCustomSpaceRequest');
goog.require('proto.api_proto.GetBulkSpaceDetailsRequest');
goog.require('proto.api_proto.GetNearbySpaceRequest');
goog.require('proto.api_proto.GetSpaceDetailsRequest');
goog.require('proto.api_proto.SearchSpaceByNameRequest');
goog.require('proto.api_proto.UpdateCustomSpaceRequest');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api_proto.SpaceServerRequests = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.api_proto.SpaceServerRequests.oneofGroups_);
};
goog.inherits(proto.api_proto.SpaceServerRequests, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api_proto.SpaceServerRequests.displayName = 'proto.api_proto.SpaceServerRequests';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.api_proto.SpaceServerRequests.oneofGroups_ = [[1,2,3,4,5,6]];

/**
 * @enum {number}
 */
proto.api_proto.SpaceServerRequests.RequestCase = {
  REQUEST_NOT_SET: 0,
  SEARCH: 1,
  GETSPACEDETAIL: 2,
  GETNEARBYSPACES: 3,
  ADDCUSTOMSPACE: 4,
  GETBULKSPACEDETAIL: 5,
  UPDATECUSTOMSPACE: 6
};

/**
 * @return {proto.api_proto.SpaceServerRequests.RequestCase}
 */
proto.api_proto.SpaceServerRequests.prototype.getRequestCase = function() {
  return /** @type {proto.api_proto.SpaceServerRequests.RequestCase} */(jspb.Message.computeOneofCase(this, proto.api_proto.SpaceServerRequests.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api_proto.SpaceServerRequests.prototype.toObject = function(opt_includeInstance) {
  return proto.api_proto.SpaceServerRequests.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api_proto.SpaceServerRequests} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.SpaceServerRequests.toObject = function(includeInstance, msg) {
  var f, obj = {
    search: (f = msg.getSearch()) && proto.api_proto.SearchSpaceByNameRequest.toObject(includeInstance, f),
    getspacedetail: (f = msg.getGetspacedetail()) && proto.api_proto.GetSpaceDetailsRequest.toObject(includeInstance, f),
    getnearbyspaces: (f = msg.getGetnearbyspaces()) && proto.api_proto.GetNearbySpaceRequest.toObject(includeInstance, f),
    addcustomspace: (f = msg.getAddcustomspace()) && proto.api_proto.AddCustomSpaceRequest.toObject(includeInstance, f),
    getbulkspacedetail: (f = msg.getGetbulkspacedetail()) && proto.api_proto.GetBulkSpaceDetailsRequest.toObject(includeInstance, f),
    updatecustomspace: (f = msg.getUpdatecustomspace()) && proto.api_proto.UpdateCustomSpaceRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api_proto.SpaceServerRequests}
 */
proto.api_proto.SpaceServerRequests.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api_proto.SpaceServerRequests;
  return proto.api_proto.SpaceServerRequests.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api_proto.SpaceServerRequests} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api_proto.SpaceServerRequests}
 */
proto.api_proto.SpaceServerRequests.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api_proto.SearchSpaceByNameRequest;
      reader.readMessage(value,proto.api_proto.SearchSpaceByNameRequest.deserializeBinaryFromReader);
      msg.setSearch(value);
      break;
    case 2:
      var value = new proto.api_proto.GetSpaceDetailsRequest;
      reader.readMessage(value,proto.api_proto.GetSpaceDetailsRequest.deserializeBinaryFromReader);
      msg.setGetspacedetail(value);
      break;
    case 3:
      var value = new proto.api_proto.GetNearbySpaceRequest;
      reader.readMessage(value,proto.api_proto.GetNearbySpaceRequest.deserializeBinaryFromReader);
      msg.setGetnearbyspaces(value);
      break;
    case 4:
      var value = new proto.api_proto.AddCustomSpaceRequest;
      reader.readMessage(value,proto.api_proto.AddCustomSpaceRequest.deserializeBinaryFromReader);
      msg.setAddcustomspace(value);
      break;
    case 5:
      var value = new proto.api_proto.GetBulkSpaceDetailsRequest;
      reader.readMessage(value,proto.api_proto.GetBulkSpaceDetailsRequest.deserializeBinaryFromReader);
      msg.setGetbulkspacedetail(value);
      break;
    case 6:
      var value = new proto.api_proto.UpdateCustomSpaceRequest;
      reader.readMessage(value,proto.api_proto.UpdateCustomSpaceRequest.deserializeBinaryFromReader);
      msg.setUpdatecustomspace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api_proto.SpaceServerRequests.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api_proto.SpaceServerRequests.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api_proto.SpaceServerRequests} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.SpaceServerRequests.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSearch();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api_proto.SearchSpaceByNameRequest.serializeBinaryToWriter
    );
  }
  f = message.getGetspacedetail();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.api_proto.GetSpaceDetailsRequest.serializeBinaryToWriter
    );
  }
  f = message.getGetnearbyspaces();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.api_proto.GetNearbySpaceRequest.serializeBinaryToWriter
    );
  }
  f = message.getAddcustomspace();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.api_proto.AddCustomSpaceRequest.serializeBinaryToWriter
    );
  }
  f = message.getGetbulkspacedetail();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.api_proto.GetBulkSpaceDetailsRequest.serializeBinaryToWriter
    );
  }
  f = message.getUpdatecustomspace();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.api_proto.UpdateCustomSpaceRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional SearchSpaceByNameRequest search = 1;
 * @return {?proto.api_proto.SearchSpaceByNameRequest}
 */
proto.api_proto.SpaceServerRequests.prototype.getSearch = function() {
  return /** @type{?proto.api_proto.SearchSpaceByNameRequest} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.SearchSpaceByNameRequest, 1));
};


/**
 * @param {?proto.api_proto.SearchSpaceByNameRequest|undefined} value
 * @return {!proto.api_proto.SpaceServerRequests} returns this
*/
proto.api_proto.SpaceServerRequests.prototype.setSearch = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.api_proto.SpaceServerRequests.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.SpaceServerRequests} returns this
 */
proto.api_proto.SpaceServerRequests.prototype.clearSearch = function() {
  return this.setSearch(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.SpaceServerRequests.prototype.hasSearch = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GetSpaceDetailsRequest getspacedetail = 2;
 * @return {?proto.api_proto.GetSpaceDetailsRequest}
 */
proto.api_proto.SpaceServerRequests.prototype.getGetspacedetail = function() {
  return /** @type{?proto.api_proto.GetSpaceDetailsRequest} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.GetSpaceDetailsRequest, 2));
};


/**
 * @param {?proto.api_proto.GetSpaceDetailsRequest|undefined} value
 * @return {!proto.api_proto.SpaceServerRequests} returns this
*/
proto.api_proto.SpaceServerRequests.prototype.setGetspacedetail = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.api_proto.SpaceServerRequests.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.SpaceServerRequests} returns this
 */
proto.api_proto.SpaceServerRequests.prototype.clearGetspacedetail = function() {
  return this.setGetspacedetail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.SpaceServerRequests.prototype.hasGetspacedetail = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional GetNearbySpaceRequest getNearbyspaces = 3;
 * @return {?proto.api_proto.GetNearbySpaceRequest}
 */
proto.api_proto.SpaceServerRequests.prototype.getGetnearbyspaces = function() {
  return /** @type{?proto.api_proto.GetNearbySpaceRequest} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.GetNearbySpaceRequest, 3));
};


/**
 * @param {?proto.api_proto.GetNearbySpaceRequest|undefined} value
 * @return {!proto.api_proto.SpaceServerRequests} returns this
*/
proto.api_proto.SpaceServerRequests.prototype.setGetnearbyspaces = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.api_proto.SpaceServerRequests.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.SpaceServerRequests} returns this
 */
proto.api_proto.SpaceServerRequests.prototype.clearGetnearbyspaces = function() {
  return this.setGetnearbyspaces(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.SpaceServerRequests.prototype.hasGetnearbyspaces = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AddCustomSpaceRequest addcustomspace = 4;
 * @return {?proto.api_proto.AddCustomSpaceRequest}
 */
proto.api_proto.SpaceServerRequests.prototype.getAddcustomspace = function() {
  return /** @type{?proto.api_proto.AddCustomSpaceRequest} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.AddCustomSpaceRequest, 4));
};


/**
 * @param {?proto.api_proto.AddCustomSpaceRequest|undefined} value
 * @return {!proto.api_proto.SpaceServerRequests} returns this
*/
proto.api_proto.SpaceServerRequests.prototype.setAddcustomspace = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.api_proto.SpaceServerRequests.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.SpaceServerRequests} returns this
 */
proto.api_proto.SpaceServerRequests.prototype.clearAddcustomspace = function() {
  return this.setAddcustomspace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.SpaceServerRequests.prototype.hasAddcustomspace = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional GetBulkSpaceDetailsRequest getbulkspacedetail = 5;
 * @return {?proto.api_proto.GetBulkSpaceDetailsRequest}
 */
proto.api_proto.SpaceServerRequests.prototype.getGetbulkspacedetail = function() {
  return /** @type{?proto.api_proto.GetBulkSpaceDetailsRequest} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.GetBulkSpaceDetailsRequest, 5));
};


/**
 * @param {?proto.api_proto.GetBulkSpaceDetailsRequest|undefined} value
 * @return {!proto.api_proto.SpaceServerRequests} returns this
*/
proto.api_proto.SpaceServerRequests.prototype.setGetbulkspacedetail = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.api_proto.SpaceServerRequests.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.SpaceServerRequests} returns this
 */
proto.api_proto.SpaceServerRequests.prototype.clearGetbulkspacedetail = function() {
  return this.setGetbulkspacedetail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.SpaceServerRequests.prototype.hasGetbulkspacedetail = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional UpdateCustomSpaceRequest updatecustomspace = 6;
 * @return {?proto.api_proto.UpdateCustomSpaceRequest}
 */
proto.api_proto.SpaceServerRequests.prototype.getUpdatecustomspace = function() {
  return /** @type{?proto.api_proto.UpdateCustomSpaceRequest} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.UpdateCustomSpaceRequest, 6));
};


/**
 * @param {?proto.api_proto.UpdateCustomSpaceRequest|undefined} value
 * @return {!proto.api_proto.SpaceServerRequests} returns this
*/
proto.api_proto.SpaceServerRequests.prototype.setUpdatecustomspace = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.api_proto.SpaceServerRequests.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.SpaceServerRequests} returns this
 */
proto.api_proto.SpaceServerRequests.prototype.clearUpdatecustomspace = function() {
  return this.setUpdatecustomspace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.SpaceServerRequests.prototype.hasUpdatecustomspace = function() {
  return jspb.Message.getField(this, 6) != null;
};


