// source: model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.api_proto.ThankYou4_2');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api_proto.FullAnswer4_2');
goog.require('proto.api_proto.User4_2');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api_proto.ThankYou4_2 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api_proto.ThankYou4_2, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api_proto.ThankYou4_2.displayName = 'proto.api_proto.ThankYou4_2';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api_proto.ThankYou4_2.prototype.toObject = function(opt_includeInstance) {
  return proto.api_proto.ThankYou4_2.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api_proto.ThankYou4_2} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.ThankYou4_2.toObject = function(includeInstance, msg) {
  var f, obj = {
    thankTime: jspb.Message.getFieldWithDefault(msg, 1, 0),
    thanker42: (f = msg.getThanker42()) && proto.api_proto.User4_2.toObject(includeInstance, f),
    fullAnswer: (f = msg.getFullAnswer()) && proto.api_proto.FullAnswer4_2.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api_proto.ThankYou4_2}
 */
proto.api_proto.ThankYou4_2.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api_proto.ThankYou4_2;
  return proto.api_proto.ThankYou4_2.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api_proto.ThankYou4_2} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api_proto.ThankYou4_2}
 */
proto.api_proto.ThankYou4_2.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setThankTime(value);
      break;
    case 2:
      var value = new proto.api_proto.User4_2;
      reader.readMessage(value,proto.api_proto.User4_2.deserializeBinaryFromReader);
      msg.setThanker42(value);
      break;
    case 3:
      var value = new proto.api_proto.FullAnswer4_2;
      reader.readMessage(value,proto.api_proto.FullAnswer4_2.deserializeBinaryFromReader);
      msg.setFullAnswer(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api_proto.ThankYou4_2.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api_proto.ThankYou4_2.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api_proto.ThankYou4_2} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.ThankYou4_2.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getThankTime();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getThanker42();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.api_proto.User4_2.serializeBinaryToWriter
    );
  }
  f = message.getFullAnswer();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.api_proto.FullAnswer4_2.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 thank_time = 1;
 * @return {number}
 */
proto.api_proto.ThankYou4_2.prototype.getThankTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.ThankYou4_2} returns this
 */
proto.api_proto.ThankYou4_2.prototype.setThankTime = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional User4_2 thanker4_2 = 2;
 * @return {?proto.api_proto.User4_2}
 */
proto.api_proto.ThankYou4_2.prototype.getThanker42 = function() {
  return /** @type{?proto.api_proto.User4_2} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.User4_2, 2));
};


/**
 * @param {?proto.api_proto.User4_2|undefined} value
 * @return {!proto.api_proto.ThankYou4_2} returns this
*/
proto.api_proto.ThankYou4_2.prototype.setThanker42 = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.ThankYou4_2} returns this
 */
proto.api_proto.ThankYou4_2.prototype.clearThanker42 = function() {
  return this.setThanker42(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.ThankYou4_2.prototype.hasThanker42 = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional FullAnswer4_2 full_answer = 3;
 * @return {?proto.api_proto.FullAnswer4_2}
 */
proto.api_proto.ThankYou4_2.prototype.getFullAnswer = function() {
  return /** @type{?proto.api_proto.FullAnswer4_2} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.FullAnswer4_2, 3));
};


/**
 * @param {?proto.api_proto.FullAnswer4_2|undefined} value
 * @return {!proto.api_proto.ThankYou4_2} returns this
*/
proto.api_proto.ThankYou4_2.prototype.setFullAnswer = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.ThankYou4_2} returns this
 */
proto.api_proto.ThankYou4_2.prototype.clearFullAnswer = function() {
  return this.setFullAnswer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.ThankYou4_2.prototype.hasFullAnswer = function() {
  return jspb.Message.getField(this, 3) != null;
};


