// source: model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.api_proto.ThankYou');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api_proto.Answer');
goog.require('proto.api_proto.Thanker');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api_proto.ThankYou = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api_proto.ThankYou, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api_proto.ThankYou.displayName = 'proto.api_proto.ThankYou';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api_proto.ThankYou.prototype.toObject = function(opt_includeInstance) {
  return proto.api_proto.ThankYou.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api_proto.ThankYou} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.ThankYou.toObject = function(includeInstance, msg) {
  var f, obj = {
    thanker: (f = msg.getThanker()) && proto.api_proto.Thanker.toObject(includeInstance, f),
    thankTime: jspb.Message.getFieldWithDefault(msg, 2, 0),
    answer: (f = msg.getAnswer()) && proto.api_proto.Answer.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api_proto.ThankYou}
 */
proto.api_proto.ThankYou.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api_proto.ThankYou;
  return proto.api_proto.ThankYou.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api_proto.ThankYou} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api_proto.ThankYou}
 */
proto.api_proto.ThankYou.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api_proto.Thanker;
      reader.readMessage(value,proto.api_proto.Thanker.deserializeBinaryFromReader);
      msg.setThanker(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setThankTime(value);
      break;
    case 3:
      var value = new proto.api_proto.Answer;
      reader.readMessage(value,proto.api_proto.Answer.deserializeBinaryFromReader);
      msg.setAnswer(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api_proto.ThankYou.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api_proto.ThankYou.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api_proto.ThankYou} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.ThankYou.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getThanker();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api_proto.Thanker.serializeBinaryToWriter
    );
  }
  f = message.getThankTime();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getAnswer();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.api_proto.Answer.serializeBinaryToWriter
    );
  }
};


/**
 * optional Thanker thanker = 1;
 * @return {?proto.api_proto.Thanker}
 */
proto.api_proto.ThankYou.prototype.getThanker = function() {
  return /** @type{?proto.api_proto.Thanker} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.Thanker, 1));
};


/**
 * @param {?proto.api_proto.Thanker|undefined} value
 * @return {!proto.api_proto.ThankYou} returns this
*/
proto.api_proto.ThankYou.prototype.setThanker = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.ThankYou} returns this
 */
proto.api_proto.ThankYou.prototype.clearThanker = function() {
  return this.setThanker(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.ThankYou.prototype.hasThanker = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint64 thank_time = 2;
 * @return {number}
 */
proto.api_proto.ThankYou.prototype.getThankTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.ThankYou} returns this
 */
proto.api_proto.ThankYou.prototype.setThankTime = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional Answer answer = 3;
 * @return {?proto.api_proto.Answer}
 */
proto.api_proto.ThankYou.prototype.getAnswer = function() {
  return /** @type{?proto.api_proto.Answer} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.Answer, 3));
};


/**
 * @param {?proto.api_proto.Answer|undefined} value
 * @return {!proto.api_proto.ThankYou} returns this
*/
proto.api_proto.ThankYou.prototype.setAnswer = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.ThankYou} returns this
 */
proto.api_proto.ThankYou.prototype.clearAnswer = function() {
  return this.setAnswer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.ThankYou.prototype.hasAnswer = function() {
  return jspb.Message.getField(this, 3) != null;
};


