// source: model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.api_proto.TransactionView');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api_proto.User');

goog.forwardDeclare('proto.api_proto.TransactionStatus');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api_proto.TransactionView = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api_proto.TransactionView, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api_proto.TransactionView.displayName = 'proto.api_proto.TransactionView';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api_proto.TransactionView.prototype.toObject = function(opt_includeInstance) {
  return proto.api_proto.TransactionView.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api_proto.TransactionView} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.TransactionView.toObject = function(includeInstance, msg) {
  var f, obj = {
    other: (f = msg.getOther()) && proto.api_proto.User.toObject(includeInstance, f),
    diff: jspb.Message.getFieldWithDefault(msg, 2, 0),
    createdAt: jspb.Message.getFieldWithDefault(msg, 3, 0),
    statusUpdatedAt: jspb.Message.getFieldWithDefault(msg, 4, 0),
    status: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api_proto.TransactionView}
 */
proto.api_proto.TransactionView.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api_proto.TransactionView;
  return proto.api_proto.TransactionView.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api_proto.TransactionView} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api_proto.TransactionView}
 */
proto.api_proto.TransactionView.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api_proto.User;
      reader.readMessage(value,proto.api_proto.User.deserializeBinaryFromReader);
      msg.setOther(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setDiff(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCreatedAt(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setStatusUpdatedAt(value);
      break;
    case 5:
      var value = /** @type {!proto.api_proto.TransactionStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api_proto.TransactionView.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api_proto.TransactionView.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api_proto.TransactionView} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.TransactionView.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOther();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api_proto.User.serializeBinaryToWriter
    );
  }
  f = message.getDiff();
  if (f !== 0) {
    writer.writeSint32(
      2,
      f
    );
  }
  f = message.getCreatedAt();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getStatusUpdatedAt();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * optional User other = 1;
 * @return {?proto.api_proto.User}
 */
proto.api_proto.TransactionView.prototype.getOther = function() {
  return /** @type{?proto.api_proto.User} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.User, 1));
};


/**
 * @param {?proto.api_proto.User|undefined} value
 * @return {!proto.api_proto.TransactionView} returns this
*/
proto.api_proto.TransactionView.prototype.setOther = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.TransactionView} returns this
 */
proto.api_proto.TransactionView.prototype.clearOther = function() {
  return this.setOther(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.TransactionView.prototype.hasOther = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional sint32 diff = 2;
 * @return {number}
 */
proto.api_proto.TransactionView.prototype.getDiff = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.TransactionView} returns this
 */
proto.api_proto.TransactionView.prototype.setDiff = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 created_at = 3;
 * @return {number}
 */
proto.api_proto.TransactionView.prototype.getCreatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.TransactionView} returns this
 */
proto.api_proto.TransactionView.prototype.setCreatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint64 status_updated_at = 4;
 * @return {number}
 */
proto.api_proto.TransactionView.prototype.getStatusUpdatedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.TransactionView} returns this
 */
proto.api_proto.TransactionView.prototype.setStatusUpdatedAt = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional TransactionStatus status = 5;
 * @return {!proto.api_proto.TransactionStatus}
 */
proto.api_proto.TransactionView.prototype.getStatus = function() {
  return /** @type {!proto.api_proto.TransactionStatus} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.api_proto.TransactionStatus} value
 * @return {!proto.api_proto.TransactionView} returns this
 */
proto.api_proto.TransactionView.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


