// source: model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.api_proto.UserBadge');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api_proto.Badge');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api_proto.UserBadge = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api_proto.UserBadge, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api_proto.UserBadge.displayName = 'proto.api_proto.UserBadge';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api_proto.UserBadge.prototype.toObject = function(opt_includeInstance) {
  return proto.api_proto.UserBadge.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api_proto.UserBadge} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.UserBadge.toObject = function(includeInstance, msg) {
  var f, obj = {
    badge: (f = msg.getBadge()) && proto.api_proto.Badge.toObject(includeInstance, f),
    progressFill: jspb.Message.getFieldWithDefault(msg, 2, 0),
    progressMax: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api_proto.UserBadge}
 */
proto.api_proto.UserBadge.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api_proto.UserBadge;
  return proto.api_proto.UserBadge.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api_proto.UserBadge} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api_proto.UserBadge}
 */
proto.api_proto.UserBadge.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api_proto.Badge;
      reader.readMessage(value,proto.api_proto.Badge.deserializeBinaryFromReader);
      msg.setBadge(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setProgressFill(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setProgressMax(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api_proto.UserBadge.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api_proto.UserBadge.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api_proto.UserBadge} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.UserBadge.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBadge();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api_proto.Badge.serializeBinaryToWriter
    );
  }
  f = message.getProgressFill();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getProgressMax();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * optional Badge badge = 1;
 * @return {?proto.api_proto.Badge}
 */
proto.api_proto.UserBadge.prototype.getBadge = function() {
  return /** @type{?proto.api_proto.Badge} */ (
    jspb.Message.getWrapperField(this, proto.api_proto.Badge, 1));
};


/**
 * @param {?proto.api_proto.Badge|undefined} value
 * @return {!proto.api_proto.UserBadge} returns this
*/
proto.api_proto.UserBadge.prototype.setBadge = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api_proto.UserBadge} returns this
 */
proto.api_proto.UserBadge.prototype.clearBadge = function() {
  return this.setBadge(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api_proto.UserBadge.prototype.hasBadge = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint32 progress_fill = 2;
 * @return {number}
 */
proto.api_proto.UserBadge.prototype.getProgressFill = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.UserBadge} returns this
 */
proto.api_proto.UserBadge.prototype.setProgressFill = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 progress_max = 3;
 * @return {number}
 */
proto.api_proto.UserBadge.prototype.getProgressMax = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.UserBadge} returns this
 */
proto.api_proto.UserBadge.prototype.setProgressMax = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


