// source: model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.api_proto.User4_2');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.api_proto.User');

goog.forwardDeclare('proto.api_proto.ContributionMedal');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api_proto.User4_2 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api_proto.User4_2.repeatedFields_, null);
};
goog.inherits(proto.api_proto.User4_2, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api_proto.User4_2.displayName = 'proto.api_proto.User4_2';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api_proto.User4_2.repeatedFields_ = [10,12,14];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api_proto.User4_2.prototype.toObject = function(opt_includeInstance) {
  return proto.api_proto.User4_2.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api_proto.User4_2} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.User4_2.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    firstName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lastName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    photoUrl: jspb.Message.getFieldWithDefault(msg, 4, ""),
    isOnboarding: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    points: jspb.Message.getFieldWithDefault(msg, 6, 0),
    numThanks: jspb.Message.getFieldWithDefault(msg, 7, 0),
    numRevokes: jspb.Message.getFieldWithDefault(msg, 8, 0),
    isAdmin: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    favoriteSpacesList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
    numAnswersGiven: jspb.Message.getFieldWithDefault(msg, 11, 0),
    previewFollowingList: jspb.Message.toObjectList(msg.getPreviewFollowingList(),
    proto.api_proto.User.toObject, includeInstance),
    followingCnt: jspb.Message.getFieldWithDefault(msg, 13, 0),
    previewFollowedList: jspb.Message.toObjectList(msg.getPreviewFollowedList(),
    proto.api_proto.User.toObject, includeInstance),
    followedCnt: jspb.Message.getFieldWithDefault(msg, 15, 0),
    medal: jspb.Message.getFieldWithDefault(msg, 17, 0),
    isOurSquad: jspb.Message.getBooleanFieldWithDefault(msg, 18, false),
    numHelped: jspb.Message.getFieldWithDefault(msg, 19, 0),
    numStreak: jspb.Message.getFieldWithDefault(msg, 20, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api_proto.User4_2}
 */
proto.api_proto.User4_2.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api_proto.User4_2;
  return proto.api_proto.User4_2.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api_proto.User4_2} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api_proto.User4_2}
 */
proto.api_proto.User4_2.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFirstName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhotoUrl(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsOnboarding(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setPoints(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNumThanks(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNumRevokes(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsAdmin(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.addFavoriteSpaces(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNumAnswersGiven(value);
      break;
    case 12:
      var value = new proto.api_proto.User;
      reader.readMessage(value,proto.api_proto.User.deserializeBinaryFromReader);
      msg.addPreviewFollowing(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFollowingCnt(value);
      break;
    case 14:
      var value = new proto.api_proto.User;
      reader.readMessage(value,proto.api_proto.User.deserializeBinaryFromReader);
      msg.addPreviewFollowed(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFollowedCnt(value);
      break;
    case 17:
      var value = /** @type {!proto.api_proto.ContributionMedal} */ (reader.readEnum());
      msg.setMedal(value);
      break;
    case 18:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsOurSquad(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNumHelped(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNumStreak(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api_proto.User4_2.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api_proto.User4_2.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api_proto.User4_2} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api_proto.User4_2.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFirstName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLastName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPhotoUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getIsOnboarding();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getPoints();
  if (f !== 0) {
    writer.writeSint32(
      6,
      f
    );
  }
  f = message.getNumThanks();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getNumRevokes();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getIsAdmin();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getFavoriteSpacesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      10,
      f
    );
  }
  f = message.getNumAnswersGiven();
  if (f !== 0) {
    writer.writeUint32(
      11,
      f
    );
  }
  f = message.getPreviewFollowingList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      proto.api_proto.User.serializeBinaryToWriter
    );
  }
  f = message.getFollowingCnt();
  if (f !== 0) {
    writer.writeUint32(
      13,
      f
    );
  }
  f = message.getPreviewFollowedList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      proto.api_proto.User.serializeBinaryToWriter
    );
  }
  f = message.getFollowedCnt();
  if (f !== 0) {
    writer.writeUint32(
      15,
      f
    );
  }
  f = message.getMedal();
  if (f !== 0.0) {
    writer.writeEnum(
      17,
      f
    );
  }
  f = message.getIsOurSquad();
  if (f) {
    writer.writeBool(
      18,
      f
    );
  }
  f = message.getNumHelped();
  if (f !== 0) {
    writer.writeUint32(
      19,
      f
    );
  }
  f = message.getNumStreak();
  if (f !== 0) {
    writer.writeUint32(
      20,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.api_proto.User4_2.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string first_name = 2;
 * @return {string}
 */
proto.api_proto.User4_2.prototype.getFirstName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setFirstName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string last_name = 3;
 * @return {string}
 */
proto.api_proto.User4_2.prototype.getLastName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setLastName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string photo_url = 4;
 * @return {string}
 */
proto.api_proto.User4_2.prototype.getPhotoUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setPhotoUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bool is_onboarding = 5;
 * @return {boolean}
 */
proto.api_proto.User4_2.prototype.getIsOnboarding = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setIsOnboarding = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional sint32 points = 6;
 * @return {number}
 */
proto.api_proto.User4_2.prototype.getPoints = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setPoints = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint32 num_thanks = 7;
 * @return {number}
 */
proto.api_proto.User4_2.prototype.getNumThanks = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setNumThanks = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional uint32 num_revokes = 8;
 * @return {number}
 */
proto.api_proto.User4_2.prototype.getNumRevokes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setNumRevokes = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional bool is_admin = 9;
 * @return {boolean}
 */
proto.api_proto.User4_2.prototype.getIsAdmin = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setIsAdmin = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * repeated string favorite_spaces = 10;
 * @return {!Array<string>}
 */
proto.api_proto.User4_2.prototype.getFavoriteSpacesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 10));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setFavoriteSpacesList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.addFavoriteSpaces = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.clearFavoriteSpacesList = function() {
  return this.setFavoriteSpacesList([]);
};


/**
 * optional uint32 num_answers_given = 11;
 * @return {number}
 */
proto.api_proto.User4_2.prototype.getNumAnswersGiven = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setNumAnswersGiven = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * repeated User preview_following = 12;
 * @return {!Array<!proto.api_proto.User>}
 */
proto.api_proto.User4_2.prototype.getPreviewFollowingList = function() {
  return /** @type{!Array<!proto.api_proto.User>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api_proto.User, 12));
};


/**
 * @param {!Array<!proto.api_proto.User>} value
 * @return {!proto.api_proto.User4_2} returns this
*/
proto.api_proto.User4_2.prototype.setPreviewFollowingList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.api_proto.User=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api_proto.User}
 */
proto.api_proto.User4_2.prototype.addPreviewFollowing = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.api_proto.User, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.clearPreviewFollowingList = function() {
  return this.setPreviewFollowingList([]);
};


/**
 * optional uint32 following_cnt = 13;
 * @return {number}
 */
proto.api_proto.User4_2.prototype.getFollowingCnt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setFollowingCnt = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * repeated User preview_followed = 14;
 * @return {!Array<!proto.api_proto.User>}
 */
proto.api_proto.User4_2.prototype.getPreviewFollowedList = function() {
  return /** @type{!Array<!proto.api_proto.User>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api_proto.User, 14));
};


/**
 * @param {!Array<!proto.api_proto.User>} value
 * @return {!proto.api_proto.User4_2} returns this
*/
proto.api_proto.User4_2.prototype.setPreviewFollowedList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.api_proto.User=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api_proto.User}
 */
proto.api_proto.User4_2.prototype.addPreviewFollowed = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.api_proto.User, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.clearPreviewFollowedList = function() {
  return this.setPreviewFollowedList([]);
};


/**
 * optional uint32 followed_cnt = 15;
 * @return {number}
 */
proto.api_proto.User4_2.prototype.getFollowedCnt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setFollowedCnt = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional ContributionMedal medal = 17;
 * @return {!proto.api_proto.ContributionMedal}
 */
proto.api_proto.User4_2.prototype.getMedal = function() {
  return /** @type {!proto.api_proto.ContributionMedal} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {!proto.api_proto.ContributionMedal} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setMedal = function(value) {
  return jspb.Message.setProto3EnumField(this, 17, value);
};


/**
 * optional bool is_our_squad = 18;
 * @return {boolean}
 */
proto.api_proto.User4_2.prototype.getIsOurSquad = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 18, false));
};


/**
 * @param {boolean} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setIsOurSquad = function(value) {
  return jspb.Message.setProto3BooleanField(this, 18, value);
};


/**
 * optional uint32 num_helped = 19;
 * @return {number}
 */
proto.api_proto.User4_2.prototype.getNumHelped = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setNumHelped = function(value) {
  return jspb.Message.setProto3IntField(this, 19, value);
};


/**
 * optional uint32 num_streak = 20;
 * @return {number}
 */
proto.api_proto.User4_2.prototype.getNumStreak = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.api_proto.User4_2} returns this
 */
proto.api_proto.User4_2.prototype.setNumStreak = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


