export default {
  SAVE: 'SAVE',
  LOAD_MOST_RECENT: 'LOAD_MOST_RECENT',
  MAIN_ERROR: 'MAIN_ERROR',

  SEND_REQUEST: 'SEND_REQUEST',
  REQUEST_SUCCESS: 'REQUEST_SUCCESS',
  REQUEST_FAILURE: 'REQUEST_FAILURE',

  EXPORT_COLLECTION: 'EXPORT_COLLECTION',
  EXPORT_CANCELLED: 'EXPORT_CANCELLED',
  EXPORT_SUCCESS: 'EXPORT_SUCCESS',
  EXPORT_ERROR: 'EXPORT_ERROR',

  IMPORT_COLLECTION: 'IMPORT_COLLECTION',
  IMPORT_CANCELLED: 'IMPORT_CANCELLED',
  IMPORT_SUCCESS: 'IMPORT_SUCCESS',
  IMPORT_ERROR: 'IMPORT_ERROR',
  READ_CACHE: 'READ_CACHE',
  REGISTER_CACHE: 'REGISTER_CACHE',
  REGISTER_CACHE_SUCCESS: 'REGISTER_CACHE_SUCCESS',
  REGISTER_CACHE_ERROR: 'REGISTER_CACHE_ERROR',
  REFRESH_CACHE: 'REFRESH_CACHE',
  REFRESH_CACHE_SUCCESS: 'REFRESH_CACHE_SUCCESS',
  REFRESH_CACHE_ERROR: 'REGISTER_CACHE_ERROR',
  SEND_CACHE_REQUEST: 'SEND_CACHE_REQUEST',
  QUERY_CACHE_SUCCESS: 'QUERY_CACHE_SUCCESS',
  QUERY_CACHE_ERROR: 'QUERY_CACHE_ERROR',
};
