export default {
  SAVE: 'SAVE',
  LOAD_MOST_RECENT: 'LOAD_MOST_RECENT',
  MAIN_ERROR: 'MAIN_ERROR',

  SEND_REQUEST: 'SEND_REQUEST',
  REQUEST_SUCCESS: 'REQUEST_SUCCESS',
  REQUEST_FAILURE: 'REQUEST_FAILURE',

  EXPORT_COLLECTION: 'EXPORT_COLLECTION',
  EXPORT_CANCELLED: 'EXPORT_CANCELLED',
  EXPORT_SUCCESS: 'EXPORT_SUCCESS',
  EXPORT_ERROR: 'EXPORT_ERROR',

  IMPORT_COLLECTION: 'IMPORT_COLLECTION',
  IMPORT_CANCELLED: 'IMPORT_CANCELLED',
  IMPORT_SUCCESS: 'IMPORT_SUCCESS',
  IMPORT_ERROR: 'IMPORT_ERROR',
};
